language: php

php:
  - 5.4
#  - 5.5
#  - 5.6
#  - 7.0

#matrix:
#  fast_finish: true
#  allow_failures:
#    - php: 7.0

env:
#  - DOCTRINE_COMMON_VERSION="~2.2.0" DB=mysql DB_USER=root PREFER=latest
#  - DOCTRINE_COMMON_VERSION="~2.3.0" DB=mysql DB_USER=root PREFER=latest
#  - DOCTRINE_COMMON_VERSION="~2.4.0" DB=mysql DB_USER=root PREFER=latest
#  - DOCTRINE_COMMON_VERSION="dev-master" DB=mysql DB_USER=root PREFER=latest
#  - DOCTRINE_COMMON_VERSION="~2.2.0" DB=pgsql PREFER=latest
#  - DOCTRINE_COMMON_VERSION="~2.3.0" DB=pgsql PREFER=latest
#  - DOCTRINE_COMMON_VERSION="~2.4.0" DB=pgsql PREFER=latest
#  - DOCTRINE_COMMON_VERSION="dev-master" DB=pgsql PREFER=latest
#  - DOCTRINE_COMMON_VERSION="~2.2.0" DB=mysql DB_USER=root PREFER=lowest
#  - DOCTRINE_COMMON_VERSION="~2.3.0" DB=mysql DB_USER=root PREFER=lowest
#  - DOCTRINE_COMMON_VERSION="~2.4.0" DB=mysql DB_USER=root PREFER=lowest
#  - DOCTRINE_COMMON_VERSION="dev-master" DB=mysql DB_USER=root PREFER=lowest
#  - DOCTRINE_COMMON_VERSION="~2.2.0" DB=pgsql PREFER=lowest
#  - DOCTRINE_COMMON_VERSION="~2.3.0" DB=pgsql PREFER=lowest
  - DOCTRINE_COMMON_VERSION="~2.4.0" DB=pgsql PREFER=lowest
#  - DOCTRINE_COMMON_VERSION="dev-master" DB=pgsql PREFER=lowest

cache:
    apt: true
    directories:
        - vendor

before_script:
  - sh -c "if [ '$DB' = 'pgsql' ]; then sudo apt-get install -y postgresql-contrib; fi"
  - sh -c "if [ '$DB' = 'pgsql' ]; then sudo /etc/init.d/postgresql reload; fi"
  - sh -c "if [ '$DB' = 'pgsql' ]; then sudo -u postgres psql -c 'create database orm_behaviors_test'; fi"
  - sh -c "if [ '$DB' = 'pgsql' ]; then sudo -u postgres psql orm_behaviors_test -c 'create extension cube'; fi"
  - sh -c "if [ '$DB' = 'pgsql' ]; then sudo -u postgres psql orm_behaviors_test -c 'create extension earthdistance'; fi"

  - sh -c "if [ '$DB' = 'mysql' ]; then mysql -e 'create database IF NOT EXISTS orm_behaviors_test' -u$DB_USER; fi"

  - composer require doctrine/common:${DOCTRINE_COMMON_VERSION}
  - sh -c "if [ '$PREFER' = 'lowest' ]; then composer update --prefer-lowest; fi"

script:
  - bin/parallel-lint -e php,phpt --exclude vendor .
  - bin/yaml-lint config/*
  - bin/phpunit --testdox
