language: php

php:
  - 5.4

before_script:
  - wget -nc http://getcomposer.org/composer.phar
  - php composer.phar install
  - psql -c 'create database orm_behaviors_test;' -U postgres
  - psql -c 'create extension cube;' -U postgres
  - psql -c 'create extension earthdistance;' -U postgres

script: phpunit

