language: php

php:
  - 5.4

before_script:
  - wget -nc http://getcomposer.org/composer.phar
  - php composer.phar install
  - sudo apt-get install -y postgresql-contrib-8.4
  - psql -U postgres -d storage -f /usr/share/postgresql/8.4/contrib/cube.sql
  - psql -U postgres -d storage -f /usr/share/postgresql/8.4/contrib/earthdistance.sql
  - createdb orm_behaviors_test

script: phpunit

