language: php

php:
  - 5.4

before_script:
  - sudo apt-get install -y postgresql-contrib-8.4
  - createuser -s -U postgres orm_user
  - psql -c 'create database orm_behaviors_test' -U orm_user
  - psql -U orm_user -d orm_behaviors_test -f /usr/share/postgresql/8.4/contrib/cube.sql
  - psql -U orm_user -d orm_behaviors_test -f /usr/share/postgresql/8.4/contrib/earthdistance.sql
  - wget -nc http://getcomposer.org/composer.phar
  - php composer.phar install

script: phpunit

