language: php

php:
  - 5.4

before_script:
  - pecl -q install mongo && echo "extension=mongo.so" >> `php --ini | grep "Loaded Configuration" | sed -e "s|.*:\s*||"`
  - sudo apt-get install -y postgresql
  - sudo /etc/init.d/postgresql reload
  - psql -c "create database orm_behaviors_test" -U postgres
  - psql orm_behaviors_test -c "create extension cube"
  - psql orm_behaviors_test -c "create extension earthdistance"
  - composer install --dev

script: phpunit

