language: php

php:
  - 5.4

before_script:
  - sudo apt-get install -y postgresql-contrib-8.4
  - 'sudo su -c "echo local all postgres trust > /etc/postgresql/8.4/main/pg_hba.conf"'
  - sudo /etc/init.d/postgresql reload
  - psql -c 'create database orm_behaviors_test' -U postgres
  - psql -U postgres -d orm_behaviors_test -f /usr/share/postgresql/8.4/contrib/cube.sql
  - psql -U postgres -d orm_behaviors_test -f /usr/share/postgresql/8.4/contrib/earthdistance.sql
  - wget -nc http://getcomposer.org/composer.phar
  - php composer.phar install

script: phpunit

