parameters:
    knp.doctrine_behaviors.reflection.is_recursive: true
    knp.doctrine_behaviors.translatable_subscriber.translatable_trait: Knp\DoctrineBehaviors\Model\Translatable\Translatable
    knp.doctrine_behaviors.translatable_subscriber.translation_trait: Knp\DoctrineBehaviors\Model\Translatable\Translation
    knp.doctrine_behaviors.translatable_subscriber.translatable_fetch_method: LAZY
    knp.doctrine_behaviors.translatable_subscriber.translation_fetch_method: LAZY
    knp.doctrine_behaviors.translatable_subscriber.is_recursive: false

    knp.doctrine_behaviors.softdeletable_subscriber.softdeletable_trait: Knp\DoctrineBehaviors\Model\SoftDeletable\SoftDeletable
    knp.doctrine_behaviors.timestampable_subscriber.timestampable_trait: Knp\DoctrineBehaviors\Model\Timestampable\Timestampable
    knp.doctrine_behaviors.timestampable_subscriber.db_field_type: datetime
    knp.doctrine_behaviors.blameable_subscriber.blameable_trait: Knp\DoctrineBehaviors\Model\Blameable\Blameable
    knp.doctrine_behaviors.blameable_subscriber.user_entity: ~
    knp.doctrine_behaviors.geocodable_subscriber.geocodable_trait: Knp\DoctrineBehaviors\Model\Geocodable\Geocodable
    knp.doctrine_behaviors.sluggable_subscriber.sluggable_trait: Knp\DoctrineBehaviors\Model\Sluggable\Sluggable
    knp.doctrine_behaviors.tree_subscriber.tree_trait: Knp\DoctrineBehaviors\Model\Tree\Node
    knp.doctrine_behaviors.sortable_subscriber.sortable_trait: Knp\DoctrineBehaviors\Model\Sortable\Sortable

services:
    Knp\DoctrineBehaviors\Reflection\ClassAnalyzer: ~

    Knp\DoctrineBehaviors\ORM\Translatable\TranslatableSubscriber:
        arguments:
            - "@knp.doctrine_behaviors.reflection.class_analyzer"
            - "@knp.doctrine_behaviors.translatable_subscriber.current_locale_callable"
            - "@knp.doctrine_behaviors.translatable_subscriber.default_locale_callable"
            - "%knp.doctrine_behaviors.translatable_subscriber.translatable_trait%"
            - "%knp.doctrine_behaviors.translatable_subscriber.translation_trait%"
            - "%knp.doctrine_behaviors.translatable_subscriber.translatable_fetch_method%"
            - "%knp.doctrine_behaviors.translatable_subscriber.translation_fetch_method%"
            - "%knp.doctrine_behaviors.translatable_subscriber.is_recursive%"
        tags:
            - { name: doctrine.event_subscriber }

    Knp\DoctrineBehaviors\ORM\Translatable\CurrentLocaleCallable:
        arguments:
            - "@service_container" # lazy request resolution

    Knp\DoctrineBehaviors\ORM\Translatable\DefaultLocaleCallable:
        arguments:
            - "%locale%"

    Knp\DoctrineBehaviors\ORM\SoftDeletable\SoftDeletableSubscriber:
        arguments:
            - "@knp.doctrine_behaviors.reflection.class_analyzer"
            - "%knp.doctrine_behaviors.reflection.is_recursive%"
            - "%knp.doctrine_behaviors.softdeletable_subscriber.softdeletable_trait%"
        tags:
            - { name: doctrine.event_subscriber }

    Knp\DoctrineBehaviors\ORM\Timestampable\TimestampableSubscriber:
        arguments:
            - "@knp.doctrine_behaviors.reflection.class_analyzer"
            - "%knp.doctrine_behaviors.reflection.is_recursive%"
            - "%knp.doctrine_behaviors.timestampable_subscriber.timestampable_trait%"
            - "%knp.doctrine_behaviors.timestampable_subscriber.db_field_type%"
        tags:
            - { name: doctrine.event_subscriber }

    Knp\DoctrineBehaviors\ORM\Tree\TreeSubscriber:
        arguments:
            - "@knp.doctrine_behaviors.reflection.class_analyzer"
            - "%knp.doctrine_behaviors.reflection.is_recursive%"
            - "%knp.doctrine_behaviors.tree_subscriber.tree_trait%"
        tags:
            - { name: doctrine.event_subscriber }

    Knp\DoctrineBehaviors\ORM\Sortable\SortableSubscriber:
        arguments:
            - "@knp.doctrine_behaviors.reflection.class_analyzer"
            - "%knp.doctrine_behaviors.reflection.is_recursive%"
            - "%knp.doctrine_behaviors.sortable_subscriber.sortable_trait%"
        tags:
            - { name: doctrine.event_subscriber }

    Knp\DoctrineBehaviors\ORM\Blameable\BlameableSubscriber:
        arguments:
            - "@knp.doctrine_behaviors.reflection.class_analyzer"
            - "%knp.doctrine_behaviors.reflection.is_recursive%"
            - "%knp.doctrine_behaviors.blameable_subscriber.blameable_trait%"
            - "@knp.doctrine_behaviors.blameable_subscriber.user_callable"
            - "%knp.doctrine_behaviors.blameable_subscriber.user_entity%"
        tags:
            - { name: doctrine.event_subscriber }

    Knp\DoctrineBehaviors\ORM\Blameable\UserCallable:
        arguments:
            - "@service_container" # because of circular dep

    Knp\DoctrineBehaviors\ORM\Loggable\LoggableSubscriber:
        arguments:
            - "@knp.doctrine_behaviors.reflection.class_analyzer"
            - "%knp.doctrine_behaviors.reflection.is_recursive%"
            - "@knp.doctrine_behaviors.loggable_subscriber.logger_callable"
        tags:
            - { name: doctrine.event_subscriber }

    Knp\DoctrineBehaviors\ORM\Loggable\LoggerCallable:
        arguments:
            - "@logger"

    Knp\DoctrineBehaviors\ORM\Geocodable\GeocodableSubscriber:
        arguments:
            - "@knp.doctrine_behaviors.reflection.class_analyzer"
            - "%knp.doctrine_behaviors.reflection.is_recursive%"
            - "%knp.doctrine_behaviors.geocodable_subscriber.geocodable_trait%"
            - "@?knp.doctrine_behaviors.geocodable_callable"
        tags:
            - { name: doctrine.event_subscriber }

    Knp\DoctrineBehaviors\ORM\Sluggable\SluggableSubscriber:
        public: false
        arguments:
            - "@knp.doctrine_behaviors.reflection.class_analyzer"
            - "%knp.doctrine_behaviors.reflection.is_recursive%"
            - "%knp.doctrine_behaviors.sluggable_subscriber.sluggable_trait%"
        tags:
            - { name: doctrine.event_subscriber }

