parameters:
    knp.doctrine_behaviors.translatable_listener.class: Knp\DoctrineBehaviors\ORM\Translatable\TranslatableListener
    knp.doctrine_behaviors.softdeletable_listener.class: Knp\DoctrineBehaviors\ORM\SoftDeletable\SoftDeletableListener
    knp.doctrine_behaviors.timestampable_listener.class: Knp\DoctrineBehaviors\ORM\Timestampable\TimestampableListener
    knp.doctrine_behaviors.blameable_listener.class: Knp\DoctrineBehaviors\ORM\Blameable\BlameableListener
    knp.doctrine_behaviors.user_entity: ~

services:
    knp.doctrine_behaviors.translatable_listener:
        class:   %knp.doctrine_behaviors.translatable_listener.class%
        public:  false
        tags:
            - { name: doctrine.event_subscriber }

    knp.doctrine_behaviors.softdeletable_listener:
        class:   %knp.doctrine_behaviors.softdeletable_listener.class%
        public:  false
        tags:
            - { name: doctrine.event_subscriber }

    knp.doctrine_behaviors.timestampable_listener:
        class:   %knp.doctrine_behaviors.timestampable_listener.class%
        public:  false
        tags:
            - { name: doctrine.event_subscriber }

    knp.doctrine_behaviors.blameable_listener:
        class:   %knp.doctrine_behaviors.blameable_listener.class%
        arguments:
            - @security.context
            - %knp.doctrine_behaviors.user_entity%
        public:  false
        tags:
            - { name: doctrine.event_subscriber }
