services:
    _defaults:
        public: true
        autowire: true
        autoconfigure: true

    Knp\DoctrineBehaviors\:
        resource: "../src"
        exclude:
            - "../src/Bundle/*"
            - "../src/Exception/*"

    Knp\DoctrineBehaviors\ORM\Translatable\TranslatableSubscriber:
        arguments:
            $translatableFetchMode: "LAZY"
            $translationFetchMode: "LAZY"

    Knp\DoctrineBehaviors\ORM\Timestampable\TimestampableSubscriber:
        arguments:
            $dbFieldType: "datetime"
