services:
    _defaults:
        public: true
        autowire: true
        autoconfigure: true
        bind:
            $translatableFetchMode: "LAZY"
            $translationFetchMode: "LAZY"

    Knp\DoctrineBehaviors\:
        resource: "../src"
        exclude:
            - "../src/Bundle/*"
            - "../src/Exception/*"
