parameters:
    doctrine_behaviors_translatable_fetch_mode: "LAZY"
    doctrine_behaviors_translation_fetch_mode: "LAZY"
    doctrine_behaviors_blameable_user_entity: ~

services:
    _defaults:
        public: true
        autowire: true
        autoconfigure: true
        bind:
            $translatableFetchMode: "%doctrine_behaviors_translatable_fetch_mode%"
            $translationFetchMode: "%doctrine_behaviors_translation_fetch_mode%"
            $blameableUserEntity: "%doctrine_behaviors_blameable_user_entity%"

    Knp\DoctrineBehaviors\:
        resource: "../src"
        exclude:
            - "../src/Bundle/*"
            - "../src/DoctrineBehaviorsBundle.php"
            - "../src/Exception/*"
